title: Fatimah Meraj
logo:/assets/img/sunglasses_suit_anime_girl_drawing_1.jpg
#description: MSC Artificial Intelligence Student
#desccription: text below image
#show_downloads: true
theme: jekyll-theme-minimal
